### ISSUE TITLE
size limit for clipboard items

### ISSUE THREAD

**Issue by b0x4it** [erebe/greenclip#100]
Is there a way to define a size limit for the clipboard items that are captured in greenclip.history?

I noticed that when I manipulate long excel sheets and copy/paste big list of data, greenclip freezes when I scroll on the items in Rofi. When this happens, clearing the history resolves the issue. But it would be great to have an option to define how large the captured items can be.

Thanks

**Comment by erebe** [comment]
Hello,
There is no size limit for now, beside the one that exist inside the X server clipboard buffer.
It should be a few mega-bytes on a modern setup.

I don't have much time at the moment, but I am keeping your request in my backlog as it makes senses

**Comment by erebe** [comment]
Done in version 4.0
the config option is `max_selection_size_bytes`
