### ISSUE TITLE
Config file reset to default (AUR version)

### ISSUE THREAD

**Issue by Oxyd76** [erebe/greenclip#102]
I will try to add app to `blacklistedApps` and change `imageCachePath` parameters, but... if i start daemon via systemd, config file parameters resets to default! If config file chmod-ed to 0440 permission, daemon failed at start.
greenclip v3.4 maked via AUR PKGBUILD tested on latest Manjaro.

**Comment by erebe** [comment]
Hello,
Greenclip rewrite the config file at startup everytime (it was to auto-update config between version) and fails if it cannot do it.
So sadly you can't chmod it to 0440 :x

**Comment by Oxyd76** [comment]
> Hello,
> Greenclip rewrite the config file at startup everytime (it was to auto-update config between version) and fails if it cannot do it.
> So sadly you can't chmod it to 0440 :x

Hmm... How do you configure the daemon then?

**Comment by erebe** [comment]
> What's the point of having a config file if it's reset everytime the daemon is started? please fix this

Thanks for asking, it was to migrate the config file painlessly for users across greenclip versions.
Feel free to submit a PR to fix this

**Comment by erebe** [comment]
fixed in version 4.0
