### ISSUE TITLE
`imageCachePath = "/tmp/greenclip/",` might be problematic.

### ISSUE THREAD

**Issue by hboetes** [erebe/greenclip#103]
Hi there,

I just read the configuration file and read this line `imageCachePath = "/tmp/greenclip/",` which is problematic for various reasons.

- You might be on a system with another user, and they can be using greenclip as well.
- You might be on a system with another user, and they can create a symlink to somewhere nasty.

Please consider using a directory in the users home, say `~/.cache` or in `~/.local/tmp`

Oh yes, there was no trailing newline at the end of the configuration file. ;)

**Comment by erebe** [comment]
You are right, but I wanted to avoid implementing the logic for cleaning the cache if something happens to the history, so I put it into `/tmp`. Also, note that on most system /tmp is a tmpfs that live in RAM, so it is quite fast to retrieve/save images.

One improvement would be to create by default a subfolder per user and put restrictive access on it.

**Comment by hboetes** [comment]
In that case consider using `mktemp(3)`

**Comment by erebe** [comment]
Fix in version 4.0.
If you don't put a trailing `/` at the end of the image_cache_directory, it will generate a mdtemp with the prefix
