### ISSUE TITLE
Allow ~ or $HOME in new configuration file

### ISSUE THREAD

**Issue by exic** [erebe/greenclip#105]
Hi,

thanks for developing greenclip! :-) I like to use it a lot.

I just upgraded to 4.0 and saw that I have to update the configuration file.
I'm syncing my configuration to various machines where $USER or $HOME will be different.
In the old config I had `~/.cache/greenclip.history` but now that doesn't seem to work any more. Can I request to get that back or is there a workaround for this?

Thanks,

Jonas

**Comment by exic** [comment]
Nevermind, I didn't restart the daemon. It still works :heart: Have a nice day!

**Comment by exic** [comment]
Oh wait, it created a `~` directory in my base dir now. So I'll have to make sure to run everything from my home dir and remove the `~/` part. But I'll reopen in case you want to handle that differently.

**Comment by erebe** [comment]
haha yes, :P 
I fixed it yesterday with this commit https://github.com/erebe/greenclip/commit/6946666a901dea32951e47a2e4e383fe2ecafc61
I just need to make a new release out of it (most likely this week-end)

if It is a major concern to you, you can download the binary from this job https://github.com/erebe/greenclip/actions/runs/814443267

**Comment by erebe** [comment]
Fixed and released in version 4.1
