### ISSUE TITLE
broken on nix because of new dependency towards xscrnsaver

### ISSUE THREAD

**Issue by teto** [erebe/greenclip#110]
Hi,

I noticed there was a new dependency added here https://github.com/erebe/greenclip/commit/bc83da8cd96612abb56cabc3c827df8bf59cc934 but I dont understand why a screensaver utility would be linked with greenclip ?
If it's a docker artifact, it shouldn't make it to the cabal description (and do we need docker to compile haskell programs now xD ?)

**Comment by erebe** [comment]
It is not used by greenclip, but the Xorg library added a dependency on it (link against it), so it is now mandatory to have it to build.

¯\_(ツ)_/¯

**Comment by teto** [comment]
for the concerned, until a PR is merged, you can add the following line to pkgs/development/haskell-modules/configuration-common.nix
```
+  greenclip = markUnbroken (addExtraLibrary super.greenclip pkgs.xlibs.libXScrnSaver);
```
