### ISSUE TITLE
[QUESTION] How to remove value from history

### ISSUE THREAD

**Issue by ChugunovRoman** [erebe/greenclip#112]
Hi, thx for greenclip. I use it with rofi, and when I copy very large text, so then the rofi menu starts freeze each time when run it.
How remove a item with large text from `greenclip.history`?

**Comment by ChugunovRoman** [comment]
And how to avoid this? Maybe cut a large string until 1000 symbols?

**Comment by b4zz4** [comment]
I think the same thing is happening to me, but it's rofi that freezes the computer.

**Comment by erebe** [comment]
Hello,

You have this option in the config file, if you want to discard large input `max_selection_size_bytes`, you need to tweak it to match your machine or put some low value like 1KB
