### ISSUE TITLE
[Feature Request] Ignore certain patterns

### ISSUE THREAD

**Issue by fdw** [erebe/greenclip#114]
Hi,

would it be possible to configure some patterns that greenclip should ignore? For example, I don't want to preserve my 2FA codes 😉

Thank you!

**Comment by erebe** [comment]
Hello,

I don't have much free time at the moment, especially since summer is coming. Your request seems legit, so I put it in the backlog, but don't expect it "soon"

**Comment by fdw** [comment]
Thank you! I'm not much of a Haskell coder, but if you can give me a pointer where to add that functionality, and if I find time, I might try myself 🙂

**Comment by erebe** [comment]
You can do the same thing than here https://github.com/erebe/greenclip/blob/master/src/Main.hs#L174
there are already max byte and blacklisted app.
Just add a new check with your regex

**Comment by erebe** [comment]
https://github.com/erebe/greenclip/issues/5
