### ISSUE TITLE
Is possible to set a static history path?

### ISSUE THREAD

**Issue by dealelopez** [erebe/greenclip#115]
In previous versions you could set a static history path in the config file
`staticHistoryPath = "~/.cache/greenclip.staticHistory",`

Was this option removed?
Can I set a static history path?

**Comment by erebe** [comment]
Hello,

the feature has been removed due to too many no-understanding / issue filled regarding this file.
So now it is embeded inside the config file

**Comment by dealelopez** [comment]
What a pity. Thanks for everything.
