### ISSUE TITLE
OSC52 paste issue

### ISSUE THREAD

**Issue by seqizz** [erebe/greenclip#116]
Hi there :wave: 

I'm using [vim-oscyank](https://github.com/ojroques/vim-oscyank) and when I copy something with it, I can't paste it outside of the origin terminal for some reason.

- I see it on the top of the list (in either rofi or `greenclip print`)
- When I run `xclip -selection clipboard -o` it gives: **Error: target STRING not available**
- Primary selection is not touched nor affected, as it should be

I am not able to paste clipboard content it unless I select it in the rofi again. Is this expected, or am I doing something wrong?

Current config:
```
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "~/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 200
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  use_primary_selection_as_input = false
  static_history = []

``` 

OS info: Nixos X11 (awesomewm)

Thanks

**Comment by erebe** [comment]
Hello,

it seems the issue is in ocsyank rather than in greenclip.
Greenclip does not take ownership of selection until you tell it to do it with rofi by selecting the entry. By default the only thing greenclip does is recording sélection every half second. 

So if you don't do anything and you see `Error: target STRING not available` it means ocsyank is not properly advertising mime type for selection.

Try by asking UTF_8 with xclip instead of the default STRING

**Comment by seqizz** [comment]
Hmm none of the available targets gave me any content:
```
innodellix ~ ~> xclip -selection clipboard -o -t text/html
Error: target text/html not available
innodellix ~ ~> xclip -selection clipboard -o -t text/plain
Error: target text/plain not available
innodellix ~ ~> xclip -selection clipboard -o -t UTF8_STRING
Error: target STRING not available
innodellix ~ ~> xclip -selection clipboard -o -t STRING
Error: target STRING not available
innodellix ~ ~> xclip -selection clipboard -o -t COMPOUND_TEXT
Error: target COMPOUND_TEXT not available
innodellix ~ ~> xclip -selection clipboard -o -t MULTIPLE
Error: target MULTIPLE not available
innodellix ~ ~> xclip -selection clipboard -o -t TEXT
Error: target TEXT not available
innodellix ~ ~> xclip -selection clipboard -o -t text/plain\;charset=utf-8
Error: target text/plain;charset=utf-8 not available
```

And this made me more confused, since I can see the content in rofi, so greenclip is aware of it somehow.

Anyway, I'll open an issue there, thanks :+1:

**Comment by erebe** [comment]
try those ones, https://github.com/erebe/greenclip/blob/ea839d653c076daf0c95a7f491ba9638fcbd050b/src/Clipboard.hs#L194

**Comment by seqizz** [comment]
All same:
```
innodellix ~ ~> for a in image/png image/jpeg image/bmp UTF8_STRING TEXT; do
xclip -selection clipboard -o -t $a
done
Error: target image/png not available
Error: target image/jpeg not available
Error: target image/bmp not available
Error: target STRING not available
Error: target TEXT not available
```

Meanwhile I can see the content on `greenclip print | head -1`. It's like something is causing X clipboard to flush after the initial copy action.

**Comment by seqizz** [comment]
Hmm I've tried different terminal emulators and an alternative clipboard manager. Same neovim and vim-oscyank setup, didn't change behaviour under tmux:

|         | Greenclip           | Clipcat  |
| ------------- |:-------------:| -----:|
| wezterm     | :no_entry:  | :ok:  |
| alacritty     | :ok:      |   :ok:  |
| konsole | :no_entry:       |   :ok:  | 
| xfce4-terminal | :no_entry:       |   :ok:  |

Not sure what alacritty is doing different so this duo works. I'd like to help if I can debug further :eyes:

**Comment by seqizz** [comment]
I guess worth re-opening, feel free to close if needed.

**Comment by erebe** [comment]
I tried with:
 - neovim + ocsyank
 - wezterm
 - greenclip the latest version

and I don't have any issue at all. I am able to paste the content outside the terminal (in my case Firefox) without any issue.

Can you provide a step by step on how to reproduce the issue ?

**Comment by seqizz** [comment]
Not sure how to exactly replicate. Here are the relevant config parts:

Neovim config related to oscyank:
```
noremap yc "+yy
autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '+' | OSCYankReg + | endif
```
Nothing special set on wezterm side, I am also using tmux but with doesn't seem to be effecting it. Once I yank it to clipboard, `greenclip print` shows it, but xclip doesn't recognize anything.

```
$ greenclip print | head -1
mods="CTRL",       action="OpenLinkAtMouseCursor",

$ for a in image/png image/jpeg image/bmp UTF8_STRING TEXT; do xclip -selection clipboard -o -t $a ;done
Error: target image/png not available
Error: target image/jpeg not available
Error: target image/bmp not available
Error: target STRING not available
Error: target TEXT not available
```

Neovim 0.5.0 and oscyank "2021-05-21"

**Comment by erebe** [comment]
> Error: target STRING not available

The target should be UTF8_STRING not STRING, can you check ?

**Comment by seqizz** [comment]
I am asking for that, but xclip responds with STRING result:
```
~> xclip -selection clipboard -o -t UTF8_STRING
Error: target STRING not available
```

Also, to make things even more colorful: I realized rarely I can paste without issues (but that seems to be totally random tbh).

**Comment by seqizz** [comment]
Alright that seems like an inconsistent environment problem overall. I've lost too much time on this so I've changed my copy-paste methods/shortcuts to enforce using clipboard in vim. So far everything works. Again, sorry for the noise and thanks for the help :facepalm:
