### ISSUE TITLE
StaticHistory with .txt files in a folder

### ISSUE THREAD

**Issue by jturnism** [erebe/greenclip#117]
This is more of a feature request, and also an issue

It would be great if we could have an option in settings or something where it parses .config/greenclip/statichistory/ for .txt files

In those text files it would be great for support with a bit longer (few paragraphs) text and new lines.
And they just show up in the clipboard history as the text file name.

Also related to issue #78 it no longer appears to work with statichistory now stored in the config file, adding a regular new line I get a config error, adding the "internal new line escape code" from the issue, I also get a config error. Both pointing to the new line part in the statichistory.

**Comment by matthewhartman** [comment]
Hey @jturnism - this is working for me. When I do the following in the config file (`~/.config/greenclip.toml`)

```
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = [
    "This is a test \n with multi \n lines \n\n cool"
  ]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
```

And I select the This is a test... snippet and paste in sublime text editor - it looks like below:

```
This is a test 
 with multi 
 lines 

 cool
```

I am using version 4.2.
