### ISSUE TITLE
[Feature Request] Mask password entry

### ISSUE THREAD

**Issue by azzamsa** [erebe/greenclip#118]
Hi, 

Is it possible to have something like:

```
[greenclip]
  mask_patern = ["pass$"]
]
```

So the `foobar123pass` will be shown as `*********` in clipboard entry?

---

Use case:

I have some scripts that send passwords to clipboards. It's very handy.
But the problem comes when I did a demo/presentation, the password will be there.

Some app has a timeout and will clear the password in the clipboard, but it doesn't work in greenclip. The password will always be there. Maybe because [deleting entry is not supported](https://github.com/erebe/greenclip/issues/63). That's why I am going with the masked option.

Thank you for greenclip. I have been using it for years.

**Comment by erebe** [comment]
Hello,

This feature has been requested a few time already, but it is not very generalizable as usually password are random, and do not contain any static prefix/suffix.

The solution, I propose, is just to freeze greenclip when you are manipulating sensitive information.
Please check https://github.com/erebe/greenclip/issues/5 to see how to freeze greenclip

**Comment by azzamsa** [comment]
Nice, idea. 
Thank you for Greenclip.
