### ISSUE TITLE
working with X selections

### ISSUE THREAD

**Issue by teto** [erebe/greenclip#12]
Is greenclip capable of saving mouse-only selections into its history, like parcellite does (the selections you can then paste with middle click) ? I love how it integrates with rofi but I miss those selections going to the clipboard history (Ctrl+C selections work fine)

Thanks for the great soft

**Comment by erebe** [comment]
I guess you are talking about when you highlight something in your terminal ?
If it is the case, it does work for me but you have to configure that in your terminal's configuration. It is up to him to merge both clipboards.

I use [st_terminal](http://st.suckless.org), if you want I can share my config

**Comment by teto** [comment]
I am thinking of X primary selection see http://vim.wikia.com/wiki/Accessing_the_system_clipboard . It's not exclusive to terminals since you can select text in eg. firefox and paste it with a middle click. Parcellite could do it with my terminal (termite).

**Comment by erebe** [comment]
Yeah I know about the primary clipboard, I made a [PR](https://github.com/Daniel-Diaz/Clipboard/blob/master/System/Clipboard/X11.hs#L103) to the upstream lib in order to paste selections also into it.
I was just not to fan about using it as a source for selection.

But I guess it is a valid use case. I will add an option in the config file in order to use it as a source.

While this being said, I will not have much free time this beginning of month. So it may take time before I release the feature.

I will keep you updated

**Comment by teto** [comment]
Great thanks !

No hurry. I am really happy with greenclip+rofi tandem.

**Comment by erebe** [comment]
I have made a [pre-release](https://github.com/erebe/greenclip/releases/download/2.0/greenclip) with the support of X Primary selection as input. Can you try it out ?

Just add `usePrimarySelectionAsInput = True` in your config file.

**Comment by teto** [comment]
Thanks a lot for this. I will try to package greenclip for nixos as this is my current OS. I am quite new to it and it's not easy so I haven't tested it yet.

**Comment by teto** [comment]
My hackish default.nix to put in greenclip folder.
```
{ haskellPackages ? (import <nixpkgs> {}).haskellPackages, 
stdenv ? (import <nixpkgs> {}).stdenv }:
# { mkDerivation, base, binary, classy-prelude, Clipboard, directory
# , microlens, microlens-mtl, stdenv, text, vector
# }:
let
  # super.haskellPackages.C
   clipboard = haskellPackages.Clipboard.overrideAttrs (oldAttrs: {
	  name = "Clipboard";
	  src = ./lib/Clipboard;
	});
in
with haskellPackages; mkDerivation {
  pname = "greenclip";
  version = "2.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base binary classy-prelude clipboard directory microlens
    microlens-mtl text vector
  ];
  # buildDepends= [ Clipboard ];
  homepage = "https://github.com/erebe/greenclip#readme";
  description = "Simple clipboard manager to be integrated with rofi";
  license = stdenv.lib.licenses.bsd3;
}
```
You can then install with `nix-env -f default.nix -i greenclip`.
I'll try to write a better one to include upstream.

Btw, primary selection works. Thanks a lot \o/

**Comment by teto** [comment]
Seems like the best way to add greenclip to nixos is to upload it on hackage (https://github.com/NixOS/cabal2nix/issues/292#issuecomment-321990177). Any thought about it ?

**Comment by erebe** [comment]
I have to look on to how compile the forked library with cabal only.

**Comment by erebe** [comment]
Done https://hackage.haskell.org/package/greenclip
Let me know if it is not working

**Comment by teto** [comment]
It's not in official nixpkgs yet but there is haskell-updates branch generated every night at
https://github.com/peti/nixpkgs.git 
A `nix-env -f "<nixpkgs>" -iA haskellPackages.greenclip` later, it seems to work pretty great !
Thanks a lot
