### ISSUE TITLE
greenclip.history lost if storage has no space left

### ISSUE THREAD

**Issue by iwconfig** [erebe/greenclip#121]
Hello,

the history file, in my case `~/.cache/greenclip.history`, seems to be overwritten with nothing if the storage device holding the file runs out of space.

Latest version of greenclip (4.2) is installed on Debian 9.

**Comment by erebe** [comment]
Hello,

Well sadly, you are not supposed to run out of disk space. A lot of programs will start to misbehave or corrupt their data if you hit  the wall at the end of your disk.

Greenclip is not going to manage this case, as it would require too much complexity to add in the tool

**Comment by iwconfig** [comment]
Aaah yep of course, that makes sense. I know this and I didn't even think of it!

I understand. Thanks for the response!
