### ISSUE TITLE
Clipboard clears upon closing source application

### ISSUE THREAD

**Issue by lucas-mior** [erebe/greenclip#123]
As an example, this program checks when selection is cleared
so that the last entry from history is added into the clipboard:
https://github.com/mrichar1/clipster
However, it is written in python so it is too much slow.
This is a known issue regarding X:
https://wiki.ubuntu.com/ClipboardPersistence

It would be nice to have this fixed on greenclip aswell.

**Comment by erebe** [comment]
Hello,
Can you please formulation your request clearly ? 
I am not sure to understand what are your expectation. 
Can you describe the behavior you would like to see ?

**Comment by lucas-mior** [comment]
Hello. I will try to explain the problem and then explain what I would like for greenclip to do:

## Description of the problem with an example.

Let's say I open a browser, select some text in it and copy into the X clipboard using `C-c`.
If I open another application, I can paste what I copied no problem whatsever,
*as long as the browser from which I copied is still open*.

If I close the browser, my clipboard will be empty (I lose whatever I had copied in that browser).

### Additional Information
That is a known issue, please check the following link:
https://wiki.ubuntu.com/ClipboardPersistence

That happens because X won't save the copied content, it just stores a reference to that data, which will be lost when the data source application is closed.

### Current solution

The solution is to use a clipboard manager. Some of those will save the copied data, so that
when the clipboard is cleared due to the closing of the program from which the data was copied,
the clipboard manager will insert that data **again** on the clipboard.

From the link (https://wiki.ubuntu.com/ClipboardPersistence) above:

```
Workaround: Clipboard Managers
If you want to fix this problem on your machine, you can install a clipboard manager that should solve it. I recommend [Parcellite](http://parcellite.sourceforge.net/?page_id=16). It's [available](http://parcellite.sourceforge.net/?page_id=10) in the universe repositories, and you can install it with:

 sudo apt-get install parcellite 

When you restart your computer or run it manually from Programs>Accessories>Parcellite, you'll have a panel applet that quietly saves a history of all your copies. You won't have to go look at the history to resurrect your copied text. Copy, quit, paste should just work.

Parcellite is also available for other distributions.

Similar programs include

Klipper, a part of KDE
Glipper, an alternative for the Gnome environment
Clipman, for XFCE
```

### Problem with the current solution
The problem is that all those programs are either bloated and slow or don't include history functionallity.
Other example is https://github.com/mrichar1/clipster,
which works exacly as I intend, however it is much slower than greenclip to open the clipboard history
(I mean like 1 second longer).

## My suggestion to greenclip is:

Include the funcionallity described above.
What I think that needs to be done is to check if the clipboard is empty in the right moment (when a window closes, for instance), and in that case insert the last entry from the history into the clipboard.

**Comment by erebe** [comment]
Ha thanks for the explanation, I understand now.
Sadly, this is not possible with greenclip.

Greenclip works a bit differently from other clipboard manager, as it never take ownership of the selection (unless you request it with greenclip print xxx), but merely record in a file at regular interval the current selection.

This is made to avoid breaking clipboard logic of applications, (i.e: Firefox can paste stuff from raw text to HTML mime)
So greenclip daemon never own/advertise the selection, so it has no way to take back ownership after you close the applications

There are some downsides to this design (ie: performance) but this is the only way to not break stuff/render clipboard on linux more broken than it is already is

**Comment by lucas-mior** [comment]
Thanks for the answer.
