### ISSUE TITLE
Broken when copying multiple lines

### ISSUE THREAD

**Issue by ch-te** [erebe/greenclip#126]
Hi,

rofi and fzf are working fine, when copying a single word or line. But when copying multiple lines, the cache is "broken" and I only see the last entry.

- I use Greenclip v4.2.
- with KDE Plasma.
- the KDE Clipboard Manager is disabled

FYI, setting 'trim_space_from_selection = false', makes it even worse. Then only copying a whole line, will break it..

Example:
- copied "jkl" and "123", which worked fine
- then copied: 
"123
456
789"

- after which, only the last entry exists. Despite, that the other entries  are still in the 'greenclip.history' file: 

`
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0123
456
789\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0123\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0jkl
`

I also cleared the history, (killed greenclip, greenclip clear, ..), which didn't help

output of `greenclip prints`: 
`123greenclip: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)`

**Comment by erebe** [comment]
I never stumbled on this kind of issue ? Are you sure it is not the app you are using that send strange stuff to the clipboard ?
