### ISSUE TITLE
It's adding entries only with terminal open

### ISSUE THREAD

**Issue by niels0n** [erebe/greenclip#129]
I'm using openbox, so no DE.
Greenclip adds new entries when I copy only when I have a terminal open with `greenclip daemon`.
Can I set it to remain enabled in background, with no need to keep the terminal open?

**Comment by tuurep** [comment]
Hey, you can add it to your autostart script at `~/.config/openbox/autostart.sh`

Add this line:

```
greenclip daemon &
```

This is how I do it on the same setup as you.

**Comment by niels0n** [comment]
okay, i'll try. thank you!
