### ISSUE TITLE
Greenclip not updating history list after update to 4.0

### ISSUE THREAD

**Issue by altosys** [erebe/greenclip#131]
I just got the update to 4.0 and found that the history is now not being updated with new entries when I copy text.
I tried both highlighting text in my terminal as well as piping output to `xclip -selection c`, both have worked before the update.
I also tried ctrl-c text in the browser, that doesn't work either.

My greenclip.toml:
```
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/tommy/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = []
  trim_space_from_selection = true
  use_primary_selection_as_input = false
```
I invoke the clipoard using this in a rofi launcher script: 
```
rofi -no-lazy-grab -theme "$theme" -kb-cancel Escape,Super_L -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
```
The greenclip.history file exists and contains some older entries, but it's not being updated.

**Comment by pc00per** [comment]
I'm on 4.2 & everything works fine. [This is my setup](https://github.com/erebe/greenclip/discussions/137#discussioncomment-3986454). I usually invoke greenclip from a script, that also tends to paste automatically when selected.
