### ISSUE TITLE
Preview the picture in the clipboard

### ISSUE THREAD

**Issue by xvrong** [erebe/greenclip#138]
Is there any way to preview the image in the clipboard showed by rofi?

**Comment by sdushantha** [comment]
This should somehow be possible since Rofi is able to display icons. Since many screenshots and images a user copies are quite large, greenclip could create thumbnails for the purpose of displaying inside rofi

**Comment by erebe** [comment]
rofi allows to display icons only in the application launcher, and only use the icons.
So it is kind of not possible in the case of greenclip as we dont use the application launcher mode to display selections
