### ISSUE TITLE
 the process occupies 1.0T memory

### ISSUE THREAD

**Issue by HighIO** [erebe/greenclip#14]
it's so weird
> $ ps aux |grep greenclip
>    7321    0.3    0.0   1073747776   3104   pts/2   S+     18:17     0:00   greenclip daemon

![htop screenshot](http://paste.opensuse.org/6abd9150)

**Comment by HighIO** [comment]
sorry for the screenshot link http://paste.opensuse.org/6abd9150

**Comment by erebe** [comment]
Hello,
This is normal and not general to greenclip but to all static haskell program.
For more info go look here: https://downloads.haskell.org/~ghc/master/users-guide/8.0.1-notes.html#runtime-system
and here https://en.wikipedia.org/wiki/Virtual_memory

For your information, Virtual memory is not what your program is really consuming, it the space that has been requested by the program to the operationg system.
Operating system are smart enough to not allocate all the ram requested by the program, and allocate it chunk by chunk lazily. 
If you want to know what a program is really using in RAM, check the RES/RSS column in htop, it is the residential memory, the one actually used.
In your case greenclip use  3.1 Mo

**Comment by HighIO** [comment]
THX
and is it possible to obfuscate history cache content instead of plain text?

**Comment by erebe** [comment]
You can encrypt the file/directory with https://wiki.archlinux.org/index.php/ECryptfs and mount the partition at startup
