### ISSUE TITLE
Rofi modes clipboard is not found

### ISSUE THREAD

**Issue by jerome-diver** [erebe/greenclip#143]
I got this Rofi error when i try to exec the rofi command from a rofi script command call.
This is my code:
``` bash
command=rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
[[ "$command" =~ .*\.sh$ ]] && xraggs -i --no-run-if-empty /bin/bash -c ${command//=} || `${command\\=}`
```
In fact, this code is a part of my code, because i get rofi dmenu from a yaml file with title and command separate by ",", then split lines to run rofi dmenu then return the command from the rofi menu selection to run the command to then... for greenclip, run rofi-greenclip menu.

But if i just run rofi command from terminal emulator directly and not from script, it does works fine.

What's going wrong with my code ?

**Comment by PRESFIL** [comment]
Looks like there are some syntactical error and I can't understand this snippet:

1. `xraggs` -> `xargs`
2. you should use double quotes and escaping in variable assignment to prevent word splitting
3. I can wind  `${command//=}` in bash man-page (but I doubt that it will work like this),
   but what is `But I doubt that it will work like this`?
4. What you want to accomplish? Put this into greenclip's config? To what variable?

What `shellcheck` says about your snippet:

```
In - line 1:
command=rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
^-- SC2037 (error): To assign the output of a command, use var=$(cmd) .


In - line 2:
[[ "$command" =~ .*\.sh$ ]] && xraggs -i --no-run-if-empty /bin/bash -c ${command//=} || `${command\\=}`
    ^------^ SC2154 (warning): command is referenced but not assigned (for output from commands, use "$(command ...)" ).
                            ^-- SC2015 (info): Note that A && B || C is not if-then-else. C may run when A is true.
                                                                        ^-----------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                                         ^-------------^ SC2092 (warning): Remove backticks to avoid executing output (or use eval if intentional).
                                                                                         ^-------------^ SC2006 (style): Use $(...) notation instead of legacy backticks `...`.

Did you mean: 
[[ "$command" =~ .*\.sh$ ]] && xraggs -i --no-run-if-empty /bin/bash -c "${command//=}" || $(${command\\=})

For more information:
  https://www.shellcheck.net/wiki/SC2037 -- To assign the output of a command...
  https://www.shellcheck.net/wiki/SC2092 -- Remove backticks to avoid executi...
  https://www.shellcheck.net/wiki/SC2154 -- command is referenced but not ass...
```
