### ISSUE TITLE
Make clipboard persist after program closes (like xclipboard)

### ISSUE THREAD

**Issue by MithicSpirit** [erebe/greenclip#145]
Using `xclipboard`, the CLIPBOARD selection is persisted even after the program that generated them is closed. I think that it would be nice if `greenclip` also did this (maybe as a config option?).

Note that the clipboard selection is saved by greenclip even when the program closes, it is just not possible to paste it again without manually restoring it with rofi/dmenu/etc., so this would just remove this somewhat annoying step.

**Comment by erebe** [comment]
Hello,

This feature is sadly not possible with greenclip due to its design. See https://github.com/erebe/greenclip/issues/123#issuecomment-1094612925 for more information
