### ISSUE TITLE
How to change the message "clipboard"

### ISSUE THREAD

**Issue by LorenRiccie** [erebe/greenclip#146]
Using rofi-greenclip with the command

`rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'`

`clipboard` is printed at the beginning of my horizontal rofi dmenu line

Is it possible to customize or remove it ?

**Comment by alba4k** [comment]
in ~/.config/rofi.rasi you can set the name you want rofi to show with 

```
{
    [...]
    display-clipboard: "TEXT";
    [...]
}
```
