### ISSUE TITLE
Works from terminal but not from keybind

### ISSUE THREAD

**Issue by niels0n** [erebe/greenclip#147]
Hi, as the title says, if I run from terminal `rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'` then it opens my clipboard as intended, then if I bind that to a key (I'm on bspwm so I'm doing it via sxhkd, if that's relevant), when I press the keys I get 

`Failed to execute: 'greenclip print'
Error: 'Failed to execute child process "greenclip" (No such file or directory)`

I already tried to put that in an executable and bind the key directly to it, but I have the same result. Still works if launched from terminal.
Do you have any idea how I could resolve this?

**Comment by erebe** [comment]
Most likely you installed greenclip in a specific location that is not present in your PATH variable when using sxhkd.
Just use the absolute path where is installed greenclip (ie: `/home/user/.local/bin/greenclip`)

**Comment by niels0n** [comment]
worked like a charm. thank you!
