### ISSUE TITLE
Support ~ expansion in config file

### ISSUE THREAD

**Issue by woefe** [erebe/greenclip#15]
When I set a path starting with `~`, `greenclip list` is always empty. For example:
```
Config {maxHistoryLength = 100, historyPath = "~/.cache/greenclip.history", staticHistoryPath = "~/.cache/greenclip.staticHistory", usePrimarySelectionAsInput = False}
```

Im using `greenclip v2.0` installed from the AUR

**Comment by erebe** [comment]
Hello,
I will have a look at it this weekend. Thanks for reporting :)
I will keep you posted

**Comment by erebe** [comment]
Should be good.
I updated the archlinux package, so `pacman -Sy greenclip` should be enough.

Let me know if it works on your side

**Comment by woefe** [comment]
Thanks! It's working on my side 👍 

I had troubles updating from the AUR, though. But I guess that was a problem with pacaur. It seems pacaur did not download the new version, because there was already an (older) version in its cache. A simple `pacaur -Sac` fixed the problem.
