### ISSUE TITLE
Compiling fails: "Not in scope: type constructur of class 'IOData'"

### ISSUE THREAD

**Issue by mrusme** [erebe/greenclip#2]
```bash
greenclip-0.1.0.0: build (exe)
Preprocessing executable 'greenclip' for greenclip-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/greenclip/greenclip-tmp/Main.o )

./greenclip/src/Main.hs:33:13: error:
    Not in scope: type constructor or class ‘IOData’
    Perhaps you meant ‘NFData’ (imported from ClassyPrelude)

--  While building package greenclip-0.1.0.0 using:
      ~/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build exe:greenclip --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

Compiling using system-wide GHC 8.0.2 with lts-8.1.

**Comment by mrusme** [comment]
Also, when running the precompile binary from the repo, the last entry it prints is always:

```
Not in scope: type constructor or class ‘IOData’
    Perhaps you meant ‘NFData’ (imported from ClassyPrelude)
```

**Comment by erebe** [comment]
Hello,

Thanks for reporting ! I haven't tried with lts-8.1 yet.
I will see that this evening when I get home.

I am a bit disturbed by your 2nd comment. Do you see the "not in scope" error message when you launch the static binary ?

**Comment by erebe** [comment]
done

**Comment by mrusme** [comment]
@erebe cool, thanks. Regarding the 2nd comment: I think I just got confused, because I copied the error message and (of course) greenclip showed it to me. Therefor I though that it was actually outputting that error message - which is not the case.
