### ISSUE TITLE
Error occurred with 3.0, either manually compiled or downloaded release

### ISSUE THREAD

**Issue by qwIvan** [erebe/greenclip#20]
greenclip: Data.Binary.Get.runGet at position 23951: Cannot decode byte '\xef': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get

**Comment by erebe** [comment]
Hello,

Can you post your greenclip.history, so I can have a look at it ?

As a workaround you can 

1. Stop all instance of greenclip
2. Delete ~/.cache/greenclip.history 
3. Restart greenclip

be sure that you do not launch 2 versions at the same time, interleave them.

**Comment by qwIvan** [comment]
It work...
Just deleted ~/.cache/greenclip.history and restart...
Troubled me for a long time...

**Comment by drasill** [comment]
I had the same error, fixed with removal of history.

**Comment by drasill** [comment]
I propose this issue to be reopened : I also have the same error when the static history contains (valid) utf-8.

I have the following in `.cache/greenclip.staticHistory` :

```
✔
✓
⚠
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.
```

It looks like `✔` and `✓` don't trigger the error, but in rofi the characters appears incorrectly (like ``).

Others, like `⚠` or` ¯\_(ツ)_/¯` trigger the error.

(Obv. it was working ok with greenclip 2)

**Comment by erebe** [comment]
@drasill Thanks for having taking time to report the issue with examples.

I will take a loot at it next week, as I don't have much time on my hand this one
