### ISSUE TITLE
What is staticHistoryPath?

### ISSUE THREAD

**Issue by qwIvan** [erebe/greenclip#21]

**Comment by erebe** [comment]
From the Readme
> Permanently set some selections to added at the end (set staticHistoryPath = your/file/with/static/entries in the config file)

Basically it's a file with one entry by line that will be always present in the end of your history.
I use it to store selection that I often need to paste.

P.s: Please next time,  add at least a sentence as a description

**Comment by qwIvan** [comment]
So.. I must to add entry to config file manually?

**Comment by erebe** [comment]
?

**Comment by qwIvan** [comment]
How to set some selections permanently?

**Comment by erebe** [comment]
> ❯ cat ~/.config/greenclip.cfg
Config {maxHistoryLength = 25, historyPath = "/home/erebe/.cache/greenclip.history", staticHistoryPath = "/home/erebe/.cache/greenclip.staticHistory", usePrimarySelectionAsInput = False}⏎

In my case I have a file at /home/erebe/.cache/greenclip.staticHistory containing (that I added manually)
> ❯ cat /home/erebe/.cache/greenclip.staticHistory
sudo systemctl
sudo journalctl -feu

so now if I do a `greenclip print` I see at the end
> .... 
sudo systemctl
sudo journalctl -feu

With rofi if you hit the upper arrow in keyboard you will go to the end of the entries
