### ISSUE TITLE
Ability to delete entries from history with a shortcut

### ISSUE THREAD

**Issue by vdemonchy** [erebe/greenclip#23]
Hello !

Rofi currently supports the `Shift+Del` shortcut to delete entries from the history of its `run` mode. Do you think it could be possible to do the same for the clipboard mode introduced with greenclip ?

Thanks !

**Comment by erebe** [comment]
It does not seem possible to handle `Shift+Del` events for plugin.
When tested, rofi does not send any inputs, so I have no way to handle this case.
Sorry ;(

**Comment by vdemonchy** [comment]
Too bad, that would have been a nice feature, thanks anyway !
