### ISSUE TITLE
[3.0-beta] greenclip clear: Prelude.undefined

### ISSUE THREAD

**Issue by BarbUk** [erebe/greenclip#24]
```
 ~ ❯ greenclip --version
greenclip v3.0 -- Recyle your clipboard selections
```
```
 ~ ❯ greenclip clear
greenclip: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at src/Debug.hs:65:13 in protolude-0.1.10-6KZ4RB9zWepBfYwAkgb4xb:Debug
```

I removed the history manually by stopping the daemon and removing ~/.cache/greenclip.history, but I have still the error after that.

**Comment by vdemonchy** [comment]
Never tried that command before with the 3.0 beta, but same error here should you need confirmation that it's not just and env issue :)

**Comment by erebe** [comment]
@BarbUk Yep sorry I forgot to remove some debugging stuff.
But even with that the clear command is not that useful, as if greenclip daemon is running it will restore the current history it has in memory.
The clear command is just there to clear the history before starting greenclip's daemon.

I will fix that next week, I don't have much time right now.

**Comment by erebe** [comment]
I am back from vacation, I will fix that during the current week

**Comment by erebe** [comment]
if you download again the 3.0-beta https://github.com/erebe/greenclip/releases/tag/3.0-beta it should be fixed
