### ISSUE TITLE
Paste right away

### ISSUE THREAD

**Issue by i-am-the-slime** [erebe/greenclip#27]
Hey, sorry if this is basic rofi knowledge. I'm quite new to this all.
Is there any way to paste the selected entry rather than just have it in the clipboard after hitting enter?
That should be the main use case, right? Or is this a problem because paste depends on the application in Linux?

**Comment by erebe** [comment]
There is no way to do it directly with greenclip/rofi as to paste something you have to know the previous window that has been focused in order to send the past event to it.

You can kind of emulate what you want with xdotool nevertheless with something like
``rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' ; xdotool type (xclip -o -selection clipboard)``
or 
``rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' ; sleep 1; xdotool type (xclip -o -selection clipboard)``

It should do what you want most of the time

**Comment by thornycrackers** [comment]
The only issue I've found with that quick snippet is that if you want to cancel out of rofi it will still paste even though you technically never chose anything. Is there a way around that?

**Comment by thornycrackers** [comment]
For anyone else looking in the future I figured it out with GPaste and this snippet

https://gist.github.com/Tadly/2d5fc5879216382acec8c09d09b6fa61

**Comment by erebe** [comment]
Thanks

**Comment by ngty** [comment]
Might be abit late, ths is what i'd done to avoid pasting previous selection on cancel.
```
#!/bin/bash

rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
sleep 0.5

# Capture the selection
TEXT="$( xclip -o -selection clipboard )"

# Only attempt to paste if there has been selection
if [ "${TEXT}x" != "x" ]; then
  xdotool type "$TEXT"

  # clear selection on paste
  echo "" | xclip -selection clipboard
fi
```

**Comment by erebe** [comment]
updated the readme, thanks

**Comment by wallace11** [comment]
@ngty 
I'm not sure why you went with that approach... You can simply compare the clipboard before and after to check if anything changed. Something like this:
```
#!/bin/bash

# Capture the current clipboard
BEFORE="$( xclip -o -selection clipboard )"

rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
sleep 0.5

# Capture the selection
TEXT="$( xclip -o -selection clipboard )"

# Only attempt to paste if there has been selection
if [ "${TEXT}" != "${BEFORE}" ]; then
  xdotool type "$TEXT"
fi
```

On a side note, I wish there was a way to get a different exit code from rofi without using the `-dmenu` option :\

**Comment by advilm** [comment]
I use `xdotool key shift+Insert` but selecting an image doesn't work if you already have an image copied for some reason.

**Comment by Guchman** [comment]
Sorry, but `xdotool type` is terrible solution. At least it's for long clipboard entries.
It would paste for eternity and if you switch focus to another field or application it would broke your system or do some unintended things...
And when I say long entry I mean 30-ish symbols. It's long enough to broke things for fast "past and switch" workflows. Copy a couple of things from web page to note-app for example.
I think it would be better to change FAQ to 
`xdotool key Ctrl+v.`

**Comment by d-asensio** [comment]
Another approach to solve this would be:

Create a sh file, something like `paste-modi.sh`
```bash
#!/usr/bin/env bash

if [ -z "$@" ]; then
  greenclip print
else
  greenclip print "$1"
  coproc (xdotool key --clearmodifiers "ctrl+v" &)
  exit 0
fi
```
> You might have to change `ctrl+v` to your configured paste keyboard shorcut

Launch greenclip as a rofi mode:
```bash
rofi -modi "paste:<path-to>/paste-modi.sh" -show paste
```

It works fine with images as well, and it is faster than using `xdotool type` and `sleep`.

Hope it helps to someone out there! :)

**Comment by QiangF** [comment]
> 

An improvement is to use the window id. (idea borrowed from emacs-everywhere)


    #!/bin/bash

    WINDOW_ID=$(xdotool getactivewindow)
    rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
    sleep 0.5

    # Capture the selection
    TEXT="$( xclip -o -selection clipboard )"

    # Only attempt to paste if there has been selection
    if [ "${TEXT}x" != "x" ]; then
        # xdotool type "$TEXT"
        xdotool windowactivate --sync $WINDOW_ID
        xdotool key --clearmodifiers Shift+Insert
        # clear selection on paste
        echo "" | xclip -selection clipboard
    fi

**Comment by pc00per** [comment]
@d-asensio your solution works but oddly switches windows. @QiangF your solution works too, but it switches too, but recovers to current window on sleeped timer. I'm not sure how to combine both of your snippets so that  window_id stays intact without any switch...
