### ISSUE TITLE
greenclip continuously prints Just " " in console

### ISSUE THREAD

**Issue by stef204** [erebe/greenclip#28]
just started to use greenclip,
as soon as I change to `usePrimarySelectionAsInput = True,` kill and restart daemon, greenclip starts to print very frequently on terminal:

`Just " "`
`Just "Firefox"`
`Just "Firefox"`
`Just "Firefox"`
`Just "Firefox"`

or some oher app.

This is even before launching the command:
`rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}`

this is the beta 3.0 on linux x86_64

**Comment by stef204** [comment]
Makes sense.
I started the daemon like this `greenclip daemon &!` and was a little surprised by the printing, which got triggered without touching keyboard/mouse.  Right after making the change to `greenclip daemon &!`, kiling and restarting--that must be the sync you mention.
Thanks for your quick turnaround on this issue.

**Comment by erebe** [comment]
You welcome
