### ISSUE TITLE
Huge virtual memory usage

### ISSUE THREAD

**Issue by mssdvd** [erebe/greenclip#29]
Currently greenclip uses 1 TB of virtual memory. It isn't a real problem but it is strange.
![image](https://user-images.githubusercontent.com/18464329/40184019-809d70ac-59ef-11e8-8dc2-fa8542647dcd.png)

**Comment by vdemonchy** [comment]
Hello, it has already been explained here why it is so: https://github.com/erebe/greenclip/issues/14 :)

**Comment by mssdvd** [comment]
Oh, I'm dumb. BTW thank you.
