### ISSUE TITLE
Feature request: allow specifying the static history path via command line

### ISSUE THREAD

**Issue by chrissound** [erebe/greenclip#33]
I often have a file open with various text to quickly copy and paste from relating to a specific project.

It would be great if I could use greenclip to use a specific file to pull entries from.

The 'staticHistoryPath' works - but it's a global file while I'm looking for a per project file.

**Comment by erebe** [comment]
You can already put in your config file something like `staticHistoryPath = "$PWD/.greenclip"` and each time you will run `greenclip print` in your terminal it will try to read the .greenclip file of your current directory if it exist.

Is this not enough ?

**Comment by chrissound** [comment]
Oh right, that could possibly work. Though I'd want to bind it to a keybinding, in which case I would not necessarily have access to set $PWD as this would be set by the windows manager / desktop environment.

**Comment by erebe** [comment]
How do invok rofi ?
Because as greenclip is a plugin, I don't control what the environnement variable will be, as it is rofi injecting them

**Comment by erebe** [comment]
An other way if you want to keep using your keybind, is to use a symbolic link.
So each time you change project you do a ` rm path_to_symbolic_file.staticHistory; ln -s $PWD/.greenclip  path_to_symbolic_file.staticHistory`

**Comment by chrissound** [comment]
`rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'`

The symbolic link sounds like a perfect work around. Many thanks! And thanks for making this - this is going to save me so much time clicks and keystrokes!
