### ISSUE TITLE
History lenght

### ISSUE THREAD

**Issue by dann1** [erebe/greenclip#36]
Hey, great clipboard manager !

Is there a way to set and or check the size of the history. I would like to know how many entries can I save. Possibly set it up to 1000.

**Comment by erebe** [comment]
Yes, just increase the number in the config file. `~/.config/greenclip.cfg`

**Comment by dann1** [comment]
can you tell me the format, I cannot find it in the README. Also where can I find more doc about this projects, since the README is the only one I've found so far.

**Comment by erebe** [comment]
I don't understand ? which format ?
The config file look like this 
```
Config {
 maxHistoryLength = 50,
 historyPath = "~/.cache/greenclip.history",
 staticHistoryPath = "~/.cache/greenclip.staticHistory",
 imageCachePath = "/tmp/",
 usePrimarySelectionAsInput = False,
 blacklistedApps = []
}
```
One is created by default when you first start greenclip. You just need to set the number you want on the line `maxHistoryLength`

**Comment by dann1** [comment]
Thanks, I didn't configure it, so I thought I had to create it.
