### ISSUE TITLE
add an option to skip re-writing the config file

### ISSUE THREAD

**Issue by kalbasit** [erebe/greenclip#39]
I'm trying to manage my Greenclip configuration using Nix home-manager, given the following

```nix
  home.file.".config/greenclip.cfg".text = ''
    Config {
      maxHistoryLength = 250,
      historyPath = "~/.cache/greenclip.history",
      staticHistoryPath = "~/.cache/greenclip.staticHistory",
      imageCachePath = "/tmp/",
      usePrimarySelectionAsInput = False,
      blacklistedApps = []
    }
  '';
```

The `.config/greenclip.cfg` is actually a symlink and the real file lives under `/nix/store` and is not writable, is it possible to add a flag (or ironically a config variable) that disables the automatic rewriting of the config file? It's currently being rewritten here https://github.com/erebe/greenclip/blob/85ec183973ec75fd6e27e95185525da337ff072f/src/Main.hs#L219-L223

**Comment by erebe** [comment]
What kind of issue is it causing you ?
Does greenclip crash ? Your file is being overwritten ? Just an error log ?

**Comment by kalbasit** [comment]
@erebe it's crashing yea.

```sh-session
$ nix-shell -p haskellPackages.greenclip --run 'greenclip print'; echo "RET=$?";
greenclip: /home/kalbasit/.config/greenclip.cfg: openFile: permission denied (Permission denied)
RET=1
```

**Comment by erebe** [comment]
You can update to the 3.2 release https://github.com/erebe/greenclip/releases/download/3.2/greenclip
The config file will not be overwritten if a valid one already exist.

You will need to add `trimSpaceFromSelection = True` in your config file in order for it to be valid with greenclip 3.2

**Comment by kalbasit** [comment]
@erebe can you please push it out to hackage so I can give it a shot? Thanks!

**Comment by erebe** [comment]
done

**Comment by kalbasit** [comment]
@erebe it's still crashing :(

```sh-session
$ /nix/store/ddn1q3xlgysp01aipqw91kvdimcl1648-greenclip-3.2.0/bin/greenclip print                                                    
greenclip: /home/kalbasit/.config/greenclip.cfg: openFile: permission denied (Permission denied)
$ ls -la ~/.config/greenclip.cfg
lrwxrwxrwx 84 kalbasit  4 Sep 10:31 /home/kalbasit/.config/greenclip.cfg -> /nix/store/360rimcvgxfx3w49spgxxlkgr33hbq9s-home-manager-files/.config/greenclip.cfg
$ ls -la `readlink -f ~/.config/greenclip.cfg`
.r--r--r-- 264 root 31 Dec  1969 /nix/store/73d0z3kgiar2almsmmy0lqsj2mb8wwfx-home_file_.configgreenclip.cfg
```

```sh-session
$ cat ~/.config/greenclip.cfg
Config {
  blacklistedApps = [],
  historyPath = "~/.cache/greenclip.history",
  imageCachePath = "/tmp/",
  maxHistoryLength = 250,
  staticHistoryPath = "~/.cache/greenclip.staticHistory",
  trimSpaceFromSelection = True,
  usePrimarySelectionAsInput = False,
}
```

**Comment by kalbasit** [comment]
@erebe never mind, it worked. I think the config file was invalid, it was not indented correctly. Here's the config file that worked:

```
Config {
 maxHistoryLength = 250,
 historyPath = "~/.cache/greenclip.history",
 staticHistoryPath = "~/.cache/greenclip.staticHistory",
 imageCachePath = "/tmp/",
 usePrimarySelectionAsInput = False,
 blacklistedApps = [],
 trimSpaceFromSelection = True
}
```
