### ISSUE TITLE
Characters remain escaped in Rofi view

### ISSUE THREAD

**Issue by owcz** [erebe/greenclip#4]
A string of Japanese characters, for instance, looks like `\12473\12540`... rather than the actual string that will paste

Quotation marks show as `\"`, etc.

**Comment by erebe** [comment]
Can you put an example of japanese string that does not work for you so I can work on it ?

For the quotation mark it is the intended behavior for now (rofi split inputs on newline, so I have to escape specials characters)
The escape character '\' will not be displayed when you paste your selection

**Comment by erebe** [comment]
I updated a new release which should add better support for Unicode (japanese), tell me if this is working for you.
https://github.com/erebe/greenclip/releases/tag/1.1

**Comment by owcz** [comment]
Nice! Works great for both quotations and Japanese (e.g., スーパーマリオブラザーズ2). Thank you

Sidenote—do you have any recommendations on how to preview larger blocks of text when only a short clip shows in the Rofi window? I don't know if there are any built-in Rofi functions that would show the larger block of text without executing on that selection but it would be quite helpful when juggling a clipboard history

**Comment by erebe** [comment]
Sorry for the late response time, I didn't see your message.
I am afraid that it is not possible with rofi sadly
