### ISSUE TITLE
Delay when searching

### ISSUE THREAD

**Issue by chrissound** [erebe/greenclip#40]
There seems to be a large delay when typing 5 or more characters for some strange reason?

When just searching for 4 characters or less it's pretty much instant.

**Comment by erebe** [comment]
Plop, 
I am in vacation but a quick answer to tell you that greenclip is not responsible for the search part, that's rofi's job.
The only command greenclip implement is displaying the full history by calling `greenclip print` beside than that rofi is doing the rest.

**Comment by chrissound** [comment]
Thanks for the answer! @erebe
