### ISSUE TITLE
Copying selected text automatically to Greenclip

### ISSUE THREAD

**Issue by dealelopez** [erebe/greenclip#42]
In previous version 2.1 I was able to automatically copying selected text to Greenclip. Is possible to achive this with version 3?

**Comment by erebe** [comment]
I don't understand.
Can you describe your workflow and what is missing ?

**Comment by erebe** [comment]
Can you check that you have `usePrimarySelectionAsInput = True` in your config file ?
I had to reset the config file with the default value when switching from 2.x to 3.x., so by default it should be to false.

**Comment by dealelopez** [comment]
Yeah, that was it.
Thanks again for the software and the support!
