### ISSUE TITLE
Rename config options

### ISSUE THREAD

**Issue by woefe** [erebe/greenclip#44]
There are three config options ending in  `...Path`. But `historyPath` and `staticHistoryPath` are files whereas `imageCachePath` is a directory. I think they should be renamed:
* `historyPath` -> `historyFile`
* `staticHistoryPath` -> `staticHistoryFile`
* `imageCachePath` -> `imageCacheDirectory`

However, this change would break existing configurations. It's just an idea for a 4.x release.

**Comment by erebe** [comment]
done in version 4.0
