### ISSUE TITLE
Ignore intermediate selections 

### ISSUE THREAD

**Issue by yzhou61** [erebe/greenclip#45]
When I select using the mouse, greenclip records one entry for each intermediate selection. For example if I drag my mouse on the text "Hello world", I'd get entries like "Hello w", then "Hello wo", and so on.

Could you add an option to ignore/remove the previous entry if it's a prefix of a subsequent entry?

**Comment by erebe** [comment]
Hello,

Sorry for the delay, for an unknown reason I haven't recieved an email notifying me of this issue.

For your question, I won't do it as I suppose that you are using the option "Use primary selection as input" and the behavior you describe is the normal one. 
I don't remember the option, but you can configure in X11 the delay into which an highlight is considered to be selected.
