### ISSUE TITLE
does not detect copying in mlterm

### ISSUE THREAD

**Issue by mt-caret** [erebe/greenclip#47]
mlterm copies by selection, but is not detected by greenclip.  Specifically, running `greenclip print` does not print the selection while `xsel -o --primary` and `xsel -o --clipboard` show it being in the clipboard.

**Comment by erebe** [comment]
Will take a look when I have time, which may not be before january

**Comment by mt-caret** [comment]
Much appreciated! In the meantime, I'll have a look at the source code to see if I can figure it out on my end.

**Comment by mt-caret** [comment]
I've decided to stick with parcellite for the time being, so I probably won't be able to help out or fix; thanks.
