### ISSUE TITLE
[Feature request] Delete or temporary disable

### ISSUE THREAD

**Issue by therockmandolinist** [erebe/greenclip#5]
Really neat clipboard manager you've made here! I was wondering if it would be possible to have a delete last item or "don't record the following copy" option. I ask since I use [pass](https://www.passwordstore.org/) as my password manager and I wouldn't want passwords sticking around in my clipboard.

The use case would be something like 
```shell
greenclip disable
# pass's clipboard copy won't be recorded
pass -c my/password
# greenclip resumes working
```
or 
```shell
pass -c my/password
greenclip delete-last
# last item is deleted from history
```
Of course, the first option would probably be best for the user, but I've no idea how any of this is implemented so, thoughts?

**Comment by erebe** [comment]
I don't think I will implement that as it is rather specific in my opinion.
But you can already do it with a shell script if you want

     ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -20
     pass -c my/password
     //do you stuff
     greenclip print flush
     ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -18

The script is retrieving the pid of the greenclip daemon and sending him the signal SIGTSTP which freeze the process.

**Comment by therockmandolinist** [comment]
Thanks, I added a `sleep 45` before `greenclip print ' '` and am content for now!

**Comment by vxcamiloxv** [comment]
This would be really useful

**Comment by brettinternet** [comment]
@vxcamiloxv Just use the commands provided by the author above.

You could even make it interactive with something like `Dunst`:

```bash
#!/bin/bash

MSG_ID='38264'
TIMEOUT=30
NAME=$(basename "$0")

# SIGTSTP to freeze process
ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -20

# If matching process is running, kill it to renew our timeout
for PID in $(pidof -x "$NAME"); do
    if [ $PID != $$ ]; then
        # Process is already running
        kill $PID
    fi
done

function revert {
    # kill subprocesses
    pkill -P $$

    # Flush selection from sleep
    greenclip print ' '

    # SIGCONT to resume process
    ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -18

    dunstify -a 'greenclipPause' -u 'low' -r "$MSG_ID" "Clipboard" "Daemon resumed."
}

trap revert INT

# race condition
dunstify -b -a 'greenclipPause' -u 'critical' -t 0 -r "$MSG_ID" "Clipboard" "Daemon paused. Dismiss to resume or wait $TIMEOUT seconds." &> /dev/null &
sleep $TIMEOUT &
wait -n

revert

exit 0
```

Whether the `sleep` finishes or `dunstify -b` is dismissed, the greenclip daemon will resume.
