### ISSUE TITLE
[Request] Persistent clipboard?

### ISSUE THREAD

**Issue by michaelplews** [erebe/greenclip#50]
It might be a useful feature to invoke persistent items that are always on the clipboard list. Is this possible with the current release?

**Comment by erebe** [comment]
Yes,
In the config file you will find an entry called `staticHistoryPath = filepath`, if you create a file at the file path location, you can set static entries (1 per line). After that when you invoke greenclip with rofi, you will always find your static entries in the end of the list of selections.
