### ISSUE TITLE
pacman for the aur?

### ISSUE THREAD

**Issue by HolyStephano** [erebe/greenclip#59]
In the readme, you say "pacman -S rofi-greenclip" for installing it from the aur. That's not how the AUR works.

**Comment by erebe** [comment]
Do you mind explaining a bit more ?

**Comment by HolyStephano** [comment]
pacman is not used to install things from the aur. it's used to install the packages that get generated by PKGBUILDs with makepkg that you get from the aur. An aur manager must be used or this must be done manually.

**Comment by erebe** [comment]
Feel free to submit a pull request to change things.

**Comment by carlf** [comment]
See #62 for a proposed clarification.

**Comment by erebe** [comment]
Thanks for the PR :)
