### ISSUE TITLE
Retrieving code snippets

### ISSUE THREAD

**Issue by owcz** [erebe/greenclip#6]
1. Copy a block of code:
```js
{
	"label": "Frieze",
	"target": "^https?://(www\\.)?frieze\\.com",
	"lastUpdated": "2017-03-12 02:26:24"
}
```

2. Retrieve a previous item (doesn't matter what)

3. Retrieve the block of code (note its tab/line break issues):

```js
{

"label": "Frieze",

"target": "^https?://(www\\.)?frieze\\.com",

"lastUpdated": "2017-03-12 02:26:24"
}
```

**Comment by erebe** [comment]
I haveto found an universal escape character :x: 
Will see that this evening

**Comment by erebe** [comment]
I updated the release 1.1 could you tell me if it is working for you ?

**Comment by owcz** [comment]
>1.1 @erebe released this 7 days ago · 14 commits to master since this release

Should there be a different experimental release [here](https://github.com/erebe/greenclip/releases)?

**Comment by erebe** [comment]
Yeah don't look at the release days, I uploaded a new binary yesterday.
I still need to bump the tag if there is a way with github
