### ISSUE TITLE
wayland / sway support

### ISSUE THREAD

**Issue by rif** [erebe/greenclip#60]
I recently moved from i3 to sway and I miss greenclip the most. Can I hope for wayland/sway support?

If it helps:

- https://github.com/bugaevc/wl-clipboard
- https://github.com/swaywm/sway/wiki/i3-Migration-Guide there is a TBD to be filled there :)

**Comment by erebe** [comment]
I already have that in my todo-list but I don't think I will add it in this project because:

- Haskell ecosystem does not have a wayland package and I don't want to maintain my own
- Would rather support wayland in a separate project as most of the complexity is handling the window manager

Sadly I don't have much free spare time at that moment, so don't expect a greenclip for wayland soon :x

**Comment by rif** [comment]
I completely understand. Thank you for taking time to create greenclip anyhow!

best regards!

**Comment by SamDc73** [comment]
any updates of on the wayland support ?

**Comment by akhiljalagam** [comment]
missing greenclip on wayland.:(

**Comment by akhiljalagam** [comment]
@asklow  
I am using this on wayland
https://github.com/yory8/clipman

**Comment by rif** [comment]
I am using clipman as well. You can re-open it if you have any hopes of it being implemented.

**Comment by luisnquin** [comment]
I hope this feature here

**Comment by erebe** [comment]
Hello,

I still don't use wayland on my computers, and I don't plan to switch anytime soon. Last time I tried, I had too many issues (nvidia card, screen resolution, ...) in order for it to be worth for me. My X11 workflow and setup is working fine so ¯\_(ツ)_/¯

All that to say, don't expect a version on greenclip for wayland anytime soon, as I have nothing to test it out.

**Comment by akhiljalagam** [comment]
As an alternative for wayland users, I recommend considering cliphist.

[cliphist](https://github.com/sentriz/cliphist#cliphist)

clipboard history “manager” for wayland
features:
- write clipboard changes to a history file
- recall history with dmenu / rofi / wofi (or whatever other picker you like)
- both text and images are supported
- clipboard is preserved byte-for-byte
    leading / trailing whitespace / no whitespace or newlines are preserved
     won’t break fancy editor selections like vim wordwise, linewise, block mode
- no concept of a picker, only pipes

requires: [go](https://golang.org/), [wl-clipboard](https://github.com/bugaevc/wl-clipboard), xdg-utils (for image mime inferance)

**Comment by luisnquin** [comment]
Yeah, I started to use *cliphist* too. Anyone having difficulty setting it up with Nix can see my setup [here](https://github.com/luisnquin/nixos-config/blob/main/home/modules/desktop/hypr/clipboard.nix).


You can also see [this](https://www.reddit.com/r/hyprland/comments/1104nba/comment/j88ofi5/?utm_source=share&utm_medium=web2x&context=3).
