### ISSUE TITLE
Overwrites my conf changes

### ISSUE THREAD

**Issue by skybert** [erebe/greenclip#64]
I've added:
```
usePrimarySelectionAsInput = True
```
To my `~/.config/greenclip.cfg` but this gets ignored by greenclip and the line is removed from the `.cfg` by greenclip. (I've got my conf in git so I can see the diff).

Versions:
```
greenclip v3.1
Xorg 7.7+19
i3 4.15.0.1-2-g1c535b18
```

My setup related to `greenclip:` https://gitlab.com/skybert/my-little-friends/commit/c22efe8f76156a43ac64d560a732add48eb720bb

**Comment by erebe** [comment]
You have twice `usePrimarySelectionAsInput` in your config file, one with True and one with False.
Can you try removing one of it ?

**Comment by skybert** [comment]
Ouch, me stupid :man_facepalming: I started `greenclip`, got a default conf file, read the documentation and added the new setting without seeing it was already there.

As a future improvement, I would suggest that `greenclip` shouldn't replace the user's conf file like this without notice, it's confusing IMHO.

Thanks for your quick response and remedy, @erebe.

**Comment by erebe** [comment]
Yep it is a poor design choice, I don't even remember why i made it that way. I think because i wanted to migrate config from version to version auto magically
