### ISSUE TITLE
Importing history

### ISSUE THREAD

**Issue by 97-109-107** [erebe/greenclip#65]
I would like to import history from another clipboard manager. When ``cat``ing that (newline delimitted) file into greenclip, I get
````
greenclip: Data.Binary.Get.runGet at position 0: not enough bytes
````
What's a safe way to import?

**Comment by erebe** [comment]
Hello,
The history of greenclip is in a binary format in order to support newline.
If you want to import your history you can do something like that

```
for line in $(cat my_old_history.file);
do
 greenclip print "$line"
 sleep 1
done
```
