### ISSUE TITLE
configuration file overwrite

### ISSUE THREAD

**Issue by muralikodali** [erebe/greenclip#66]
I am using Ubuntu Mate 18.04.02. I have recently installed greenclip. **Any changes made to configuration file are overwritten**. 
It is defaulting to " Config {maxHistoryLength = 15, historyPath = "/home/sri/.cache/greenclip.history", staticHistoryPath = "/home/sri/.cache/greenclip.staticHistory"}.

**Comment by lucas8** [comment]
After looking at the code, greenclip rewrite the config file if it was invalid, meaning it failed to be read. Furthermore the reading code is very *very* simplistic, so there is probably something wrong with the way you wrote the config file.

**Comment by erebe** [comment]
@dwarfmaster is right, your config file is most likely ill formated.
But I agree that it was not the best decision to override config file. I was mainly to avoid to deal with config version upgrade ....

**Comment by muralikodali** [comment]
my config file is changed to "Config {usePrimarySelectionAsInput = True, maxHistoryLength = 15, historyPath = "/home/sri/.cache/greenclip.history", staticHistoryPath = "/home/murali/.cache/greenclip.staticHistory"}.

It defaults back to Config {maxHistoryLength = 15, historyPath = "/home/sri/.cache/greenclip.history", staticHistoryPath = "/home/sri/.cache/greenclip.staticHistory"}

I have tried it when greenclip daemon is running and also without running and restarting the daemon to see the difference. But the result is same.

**Comment by erebe** [comment]
which version of greenclip do you have ? because it should default to a config with all the possible settings available.
My guess is that you are not using the latest version of greenclip and try to use `usePrimarySelectionAsInput`

**Comment by muralikodali** [comment]
I installed the latest version in my Ubuntu 18.04 . I am getting following error:

 Data.Binary.Get.runGet at position 80: Unknown encoding for constructor
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get

**Comment by erebe** [comment]
You need to follow the migration step as you seem to were in a 2.x version of greenclip
https://github.com/erebe/greenclip#migrating-from-2x-version-to-3x-one


    Kill all greenclip process already running
    Delete your old config file and old cache file (in ~/.cache/greenclip*)
    Start the new version of greenclip

**Comment by muralikodali** [comment]
Following your suggestions after installing latest version of greenclip and removing history file in .cache folder, now greenclip is running without any error.
