### ISSUE TITLE
staticHistory and Umlauts

### ISSUE THREAD

**Issue by benedikt-bartscher** [erebe/greenclip#68]
If there are any Umlauts (äöü) in my staticHistory rofi-greenclip does not show any entrys at all.

**Comment by erebe** [comment]
Seems similar to https://github.com/erebe/greenclip/issues/54
can you try out 
```

**Comment by benedikt-bartscher** [comment]
You are right, it's similar to #54. Iconv helps, but i don't want to do this every time i edit the static history. I use neovim and never had any problems with UTF-8 before

**Comment by erebe** [comment]
To be honest, I don't know why this happens. I don't have any issues myself while I use a French layout, like in the #54 issue.
I suppose there is something wrong with the language config of the machine, but neither took time to dig into it, as I don't see the issue.
The iconv solution is good enough workaround for me to those who hit this issue.
