### ISSUE TITLE
Can you please add a changelog

### ISSUE THREAD

**Issue by deimosfr** [erebe/greenclip#7]
Hi,

I've updated greenclip but do not know what you've added. Can you please add a changelog ?

Thanks

**Comment by erebe** [comment]
There is a changelog in the release section https://github.com/erebe/greenclip/releases

**Comment by deimosfr** [comment]
ok...thanks

**Comment by erebe** [comment]
I added one by the way in the repo and if you are using Archlinux you can do pacman -Qc greenclip to get the changelog
