### ISSUE TITLE
Executing with i3

### ISSUE THREAD

**Issue by pedrolucasp** [erebe/greenclip#70]
Hello. This is not a issue, maybe a workaround I've done to work with greenclip and i3.

So, following the simple AUR package installation didn't worked for me, it kept getting the `X display not available. Please start Xorg before running greenclip` message as @sadid mentioned on his issue #69. 

In my case, I don't have a login manager, so it only start the XServer when I log in, and the first thing it tries to start is the i3 WM with `exec i3`.

What I've done was to add this line on my i3 config:
`exec --no-startup-id greenclip daemon>/dev/null`

The `/dev/null` is important so there's no messages when selecting stuff, specially on terminals.

Hope this may add some light on this issue

**Comment by wakatara** [comment]
This was very helpful for me to get it working with i3, thank you @pedrolucasp 

However, at least on Manjaro i3 edition 20.0.3, I notice the dameon either does not survive a restart in i3 config or silently dies and then does not reload when I use an i3 reload `$mod+Shift+r`. Would love to know if you've had issues with that.

Works fine when I log out and log back in but certainly willing to help, @erebe on running down that diagnosis.

**Comment by pedrolucasp** [comment]
Glad to hear @wakatara!

I haven't had any issues regarding restarting i3 so far, it works perfectly fine, and not only on i3 
as I recently was messing around with openbox and using the same basic workaround on a script.

Sorry :cry:

**Comment by wakatara** [comment]
Hey there!

I will look into it a bit more, though it seems to be stable on startup now with the `> /dev/null` added, and a tweak I made to the X config may have stabilized things for it and some other apps (for some reason, GPU offloading apps seemed to be having issues like `kitty` and electron based ones like `VS Code`.

I will do some tracing and see if it persists or there may be an issue.

Loving it though. Is really great. I'd love to see some enhancement of the "staticHistory" capability to have it be totally great as a snippet manager though. (see my other ticket... =] ).

**Comment by wakatara** [comment]
Close this for now and reopen later if I can track anything down.  ciao!
