### ISSUE TITLE
Error running greenclip daemon

### ISSUE THREAD

**Issue by hfel** [erebe/greenclip#72]
Hi! I've been using greenclip for over a year without any issues, however a few days ago it stopped working. When I try to run the daemon, I get the following:
````
$ greenclip daemon
Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get
````
I've no idea where the problem lies; rofi itself runs fine.

**Comment by erebe** [comment]
Your history file is most likely corrupted, like in https://github.com/erebe/greenclip/issues/61
kill greenclip daemon and do a `greenclip clear` before restarting the daemon.
Should be fine after that

**Comment by hfel** [comment]
Thanks, this solved the issue!
