### ISSUE TITLE
Systemd service fails all the time

### ISSUE THREAD

**Issue by weilbith** [erebe/greenclip#75]
Hey,
following the [ArchLinux Guide for Greenclip](https://wiki.archlinux.org/index.php/Greenclip) I activated and started the user service for Systemd. Unfortunately it always fails. The output of `journalctl --user -f -u greenclip.service` is the following:

```sh
-- Logs begin at Fri 2020-01-31 22:54:25 CET. --
Feb 17 09:16:15 kautz systemd[2522]: greenclip.service: Scheduled restart job, restart counter is at 4.
Feb 17 09:16:15 kautz systemd[2522]: Stopped Greenclip agent.
Feb 17 09:16:15 kautz systemd[2522]: Started Greenclip agent.
Feb 17 09:16:15 kautz greenclip[2762]: X display not available. Please start Xorg before running greenclip
Feb 17 09:16:15 kautz systemd[2522]: greenclip.service: Succeeded.
Feb 17 09:16:15 kautz systemd[2522]: greenclip.service: Scheduled restart job, restart counter is at 5.
Feb 17 09:16:15 kautz systemd[2522]: Stopped Greenclip agent.
Feb 17 09:16:15 kautz systemd[2522]: greenclip.service: Start request repeated too quickly.
Feb 17 09:16:15 kautz systemd[2522]: greenclip.service: Failed with result 'start-limit-hit'.
Feb 17 09:16:15 kautz systemd[2522]: Failed to start Greenclip agent.
```

If I run the daemon manually (`greenclip daemon`) it works. But I would love to have it as user service. The imported service file is untouched by me from the `rofi-greenclip` package on version `v3.2-3`. I saw the discussion that the `After=display-manager.service` should solve the problem. But that fix is already part of that version and does not work for me.

```
[Unit]
Description=Greenclip agent
After=display-manager.service

[Service]
Type=simple
ExecStart=/usr/bin/greenclip daemon
Restart=always

[Install]
WantedBy=default.target
```

Any idea how to solve that problem? Thanks!

**Comment by erebe** [comment]
can't check right now as i am in vacation for a few weeks (and i don't use the systemd service).
but my guess is that the process is not launched within an X enabled context. 
try to check if you have the env variable DISPLAY set when greenclip is launched.

**Comment by weilbith** [comment]
To solution appears to be the `DBUS_SESSION_BUS_ADDRESS`. At least that was the only thing I changed in this context (because of something else) and now it works. I close this issue thereby. If anything changes or I approved that this variable was the issue I will leave a note here.

**Comment by cocoonkid** [comment]
My solution was to fix the path to the history file. The user home was set wrong after a move to another machine.
Took me ages to find out. Maybe this should be caught with proper exceptions.
