### ISSUE TITLE
Not pasting copied value

### ISSUE THREAD

**Issue by rakanalh** [erebe/greenclip#8]
Hello,

I installed greenclip, launched the daemon and i bound the command to launch rofi with the clipboard option to `Mod p`. 
When i bring up rofi and hit enter to copy a value, the selected entry doesn't get copied/moved into the clipboard. So i am always pasting an older value. Anything wrong i am doing or is this a bug?

Thanks

**Comment by erebe** [comment]
Hello,

What environment are you using (Gnome/kde/i3/...) ?
On reddit someone had a similar issue due to the fact that its environment was already providing a clipboard manager, leading to each other trying to steal the clipboard

**Comment by rakanalh** [comment]
I'll double check.. Thanks alot!

**Comment by bascht** [comment]
Just stumbled upon the same issue, in case anyone else is running KDE and greenclip doesn't paste the copied value: The built-in Clipboard manager might be interfering: (_credits to Reddit user [WozarZ](https://www.reddit.com/user/WozarZ))_:

---

> For anyone who might experience the same problem, here is how to disable it:
>   * Right-click system tray.
>   * Go to settings.
>   * Under the menu "Extra Items", uncheck "Clipboard".
