### ISSUE TITLE
Config: blacklistedApps example

### ISSUE THREAD

**Issue by SimonMonecke** [erebe/greenclip#81]
Version: 3.1
OS: Manjaro

Hi,
I love greenclip but I'm not able to blacklist applications.
As explained in the README I started the daemon in the terminal to see the name of the application I want to blacklist.
example output:
```
Just "Qt Selection Owner for enpass"
Just "Terminal"
```
Now I want to blacklist enpass and I tried different strings in the config but nothing seems to work.
```
blacklistedApps = ["Qt Selection Owner for enpass"]
blacklistedApps = ["enpass"]
blacklistedApps = ["Enpass"]
blacklistedApps = ["\"Qt Selection Owner for enpass\""]
blacklistedApps = ["Just \"Qt Selection Owner for enpass\""]
```

Do you have a hint for me how to get it working?

**Comment by erebe** [comment]
Hello,

BlacklistedApps is an array, so if you want to set multiple values you need to put a comma
```
blacklistedApps = ["Qt Selection Owner for enpass", "enpass"]
```

Regarding your case, the first version should work,
```
blacklistedApps = ["Qt Selection Owner for enpass"]
```

but be sure that it is not Terminal that is stealing your selection, if it is the case you need to blacklist it also.

**Comment by SimonMonecke** [comment]
Hi,
I've tried it again and you are right: The first version works as expected! But only if I enable `usePrimarySelectionAsInput`.
I'm fine with this even if I don't understand what this setting exactly does.
`README: Merge X Primary selection with clipboard selection`

Can you explain to me how greenclip behaves differently when I activate this setting?

Thanks! Best Regards,
Simon

**Comment by erebe** [comment]
Xorg has 2 distinct clipboards. One that is the traditional for copy/paste and another one, the primary selection, that is used when you highlight some text in an application.

By default, greenclip request only selection from the traditionnal copy/paste buffer, and let alone the primary selection buffer. But some people like that everything they highlight to get archived by greenclip. I find this feature anoying but ¯\_(ツ)_/¯

**Comment by SimonMonecke** [comment]
Thank you very much for this little linux private lesson :+1: 
And I agree with you! I don't like that setting either. I just turn it back to 'False' and the blacklisting is still working... hmm, maybe I was totally confused and didn't realize that there was already a running daemon in the background which was started without the blacklisting setting -.-
Sorry :-/ and thank you for greenclip, the smart rofi clipboard manager suiting perfectly in my setup.
Keep on going! Best regards,
Simon
