### ISSUE TITLE
coredump on boot

### ISSUE THREAD

**Issue by timonson** [erebe/greenclip#82]
I get the following error a few times in my journal on arch:

> Apr 12 23:13:58 user systemd-coredump[2564]: Process 2560 (greenclip) of user 0 dumped core.
> Stack trace of thread 2560:
> #0  0x00007f06be2b0fdb n/a (/usr/bin/greenclip + 0xdafdb)

I really don't know what this is about. Otherwise greenclip works as expected.

Let me know if you need more information. 

Thanks @erebe !

**Comment by erebe** [comment]
Well, I got a look at it and I don't have any coredump on my machine.
If greenclip is still working after boot, I am going close the issue. I don't have much time to dig in this issue sadly ;(
