### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by justahuman1** [erebe/greenclip#84]
I noticed this previously and thought it was an error. But greenclip takes 1 TB virtual memory. This is only vm, whereas cpu and actual mem % are fine (~0 actually). 

Downloaded from AUR. Running Linux 5.6.

![htop monitor](https://user-images.githubusercontent.com/40372802/80268497-44f15000-865c-11ea-9edb-27c4fac02245.png)

1.0T is the VM, 4416 is PhyM, and the 0.0's are cpu and mem.

Issue persists after kill and restart.

**Comment by justahuman1** [comment]
1.0T is the VM, 4416 is PhyM, and the 0.0's are cpu and mem.

**Comment by erebe** [comment]
Hello,
see https://github.com/erebe/greenclip/issues/14 for the answer :)
