### ISSUE TITLE
Silence `Just ""` Output Option?

### ISSUE THREAD

**Issue by alichtman** [erebe/greenclip#85]
![image](https://user-images.githubusercontent.com/20600565/87786597-d1488480-c7ff-11ea-915a-58257cb68e57.png)

When yanking things in vim (I've connected vim to my system clipboard), I see this `Just ""` message printed, overwriting some of the text in my editor.

Is there any way to silence this output?

**Comment by herod2k** [comment]
I can confirm the problem, but not in Vim, in rxvt-unicode. Everytime that I copy something somewhere, it appears **Just "NAME_OF_THE_SOFTWARE"** inside the the terminal.
Copying from Firefox and Telegram I can see:
```
~  greenclip daemon &
Just "Firefox"
Just "Qt Selection Owner for TelegramDesktop"
```

OS: archlinux
package compiled from AUR
Terminal: urxvt

Other terminals like Alacritty or Terminator don't show the same problem.

I hope that it could help.

**Comment by erebe** [comment]
It is meant to know the name of the clipboard owner in case you want to blacklist it.
It you don't want any output, just redirect everything into /dev/null 
greenclip daemon > /dev/null  2>&1

**Comment by alichtman** [comment]
```bash
if [ "$OS" = "Linux" ]; then
    pgrep sxhkd >/dev/null || (bash -c "sxhkd -r $XDG_CACHE_HOME/sxhkd.log &")
    pgrep greenclip >/dev/null || (bash -c "greenclip daemon & > /dev/null 2>&1")
fi
```

This is what I have in my `~/.zshenv`

**Comment by alichtman** [comment]
@erebe Do you have any ideas?
