### ISSUE TITLE
[FEATURE REQUEST] More structured StaticHistory file/snippets and multiline selection support

### ISSUE THREAD

**Issue by wakatara** [erebe/greenclip#86]
First off, *loving* this and rofi on my i3 system at the moment. It duplicates most of what I needed in a keyboard driven workflow like Alfred's clip and snippets manager on OSX. 

For more elaborate snippets in the static history, it would be nice if "multiline" snippets in StaticHistory (which I call greenclipsnips :stuck_out_tongue_winking_eye: ) could support multiline snippets (ie. selections with line breaks in them) but somehow show a digest of the selection or otherwise show the selection on one line in the rofi indicator.

Secondly, it was totally unclear to me what the separator for selections was from the documentation (and apologies if I missed it) between selections. Looking at the cache.History file it appears to be `^@^@^@^@^@^@^@^@^@` a number of times? Is there some other demarcation we could use to be more explicit? (is there a reason for that or is it some strange sort of thing with cahce files?

(The only other wishlist thing I would love here would be a way to have selection evaluated in a super basic sort of template sort of way... so something like a `{{ date %Y-%m-%d }}` could be passed along to expand a small selection of super basic shortcodes for the snippet. Or some lever way to pull that off.).

thanks for all your clever on this. Really great tool.

**Comment by erebe** [comment]
Hello,

For the multiline in static history file, it is wanky but already possible. Please see https://github.com/erebe/greenclip/issues/78

Regarding the second question, the history file is a binary format. So it is not meant to be edited/modified outside greenclip, that why there is the static history file to allow a more friendly addition of snippets.

For the wishlist, you can do it but you need to glue things by yourself.
For example, if you have in your selection

> hello from $(date)

You can do your template engine with something like

> greenclip print | fzf | xargs -I R /bin/sh -c "echo R"
> hello from Sun 09 Aug 2020 12:54:57 PM CEST

**Comment by wakatara** [comment]
I see. Considering this is something that I imagine quite a few people would want, might it not be better to add support for a yaml or toml file in order to make this easier to configure and maintain? (hehehe... I like the way you called it wanky. =p ).

This would seriously make it considerably user friendly (as I did not see this, I kind of wrote a template in emacs lisp). Unfortunately as the code base is in Haskell I can't just wade in and add this like I would go, crystal, or such... :-/ 

(I am also seriously in awe od you puzzling out the templating that way... =]  Impressive. That would work more or less once I sort out a strftime on that... =] ). 

thanks for the quick response! I seriously do like the program. Super handy so thanks for all your work on this!  (going to puzzle out how to get it working with xdotool to do direct pastes next... =] ).

**Comment by wakatara** [comment]
(the other possibility to implement this better/quicker *might* just be to just have individual lines in the static history file point at a file reference that got plugged in. That may be the easiest way to handle this... I know that's what I just did in emacs rather than try to do a big one line `\n\n` multtiple times for a line and try to figure out org-capture's syntax...

Easier. quicker. I'd assume. Also, perhaps a little cleaner since we all love text files.  =]

**Comment by erebe** [comment]
I don't work much on greenclip anymore, I will add your request in the backlog. Eventually, I would like to replace the config file and static history by a yaml file, but it will introduce some breaking changes :x 
It is planned, but when it will happen/have time, I can't tell you

**Comment by erebe** [comment]
Done in version 4.0
you can use toml format in config file now, like this
```
static_history = [
 '''¯\_(ツ)_/¯''',
]
```

**Comment by Daryl-DH** [comment]
Thank you!
