### ISSUE TITLE
[FEATURE] Flatpak or deb/apt repo?

### ISSUE THREAD

**Issue by wakatara** [erebe/greenclip#89]
Yes, I know it's a static binary and all, but I think you could really drive some more adoption if standard ways of installing this beyond `yay` on Arch/Majaro were used. 

Would it be possible to flatpak this for greater reach?

Failing that, perhaps an apt ppa since Ubuntu distros cover the greatest ground?

**Comment by erebe** [comment]
Hello,

I understand the need but sadly I don't want maintain this by myself. So it will not going to happen ;(
