### ISSUE TITLE
Disable all imagea

### ISSUE THREAD

**Issue by strogiyotec** [erebe/greenclip#90]
Good day, I do use awesome wm and do screenshots using [flameshot](https://github.com/flameshot-org/flameshot). I don't need to keep a history of images in greenclip so I wonder what would be the best option 

1. Add flameshot to blacklist
2. Somehow tell greenclip to avoid all images

Please tell me if second option is achievable using config otherwise I will go with the first one

**Comment by erebe** [comment]
Hello,
It is not possible to disable images history in greenclip, so you are left with the first option :)

**Comment by strogiyotec** [comment]
Ok thanks

**Comment by therajat08** [comment]
> Good day, I do use awesome wm and do screenshots using [flameshot](https://github.com/flameshot-org/flameshot). I don't need to keep a history of images in greenclip so I wonder what would be the best option
> 
> 1. Add flameshot to blacklist
> 2. Somehow tell greenclip to avoid all images
> 
> Please tell me if second option is achievable using config otherwise I will go with the first one

Coincidentally, i also use awesome and flameshot, what did you to exclude flameshot? I cant get it to work
