### ISSUE TITLE
Pasting to electron based apps , firefox and chrome.

### ISSUE THREAD

**Issue by bechampion** [erebe/greenclip#91]
Hey guys.

Im using greenclip 3.3 and depending on the size of the image i screenshot and send to xclip , when i paste it on slack/firefox/chrome it lierally kills them.
If i kill greenclip daemon all works well.
This is really odd but a colleague of mine replicated it too ,  it happens in big screenshots with a lots of details , for example we were using a screenshot google maps in satellite mode (about 2MB).
I read on the githubn readme.md that greenclip skips large images ... it doesn't seem to do that for me.

Thank you

**Comment by erebe** [comment]
Hello,

Can you upload/provide me an image that create a crash on your setup ?
Also can you tell me your Os (Ubuntu, Archlinux, ...) and window manager.

Thanks for reporting
