### ISSUE TITLE
Is there a way to pipe the selection to a script on request?

### ISSUE THREAD

**Issue by eater** [erebe/greenclip#97]
I'd like to be able to set up greenclip and rofi so I can select an item from the history and then (if I want to) hit a custom key, say `Shift-Enter`, to send the selected text to a preconfigured script, for instance `upload_to_imgur.sh`. Is that possible?

**Comment by yusufaktepe** [comment]
Yes, it's possible. You need  to catch the exit code from rofi and use a simple case statement.

Here is an example:
```
#!/bin/sh

clip=$(greenclip print | sed '/^$/d' | rofi -kb-custom-1 "Alt+Return" -dmenu -i -l 10 -p Clipboard)
ret=$?

case $ret in
	10) echo "$clip" | your_script.sh ;;
	0) echo "$clip" | xargs -rd'\n' -I '{}' greenclip print '{}' ;;
esac
```

**Comment by eater** [comment]
Amazing, thanks!
