### ISSUE TITLE
Prompt parameter not working

### ISSUE THREAD

**Issue by joaopauloalbq** [erebe/greenclip#99]
For example: 
_rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}' **-p "HERE"**_

**Comment by erebe** [comment]
What is it supposed to do ?

**Comment by joaopauloalbq** [comment]
Change the string shown at the prompt

example: 
![print1](https://user-images.githubusercontent.com/9905202/112366700-e3948f80-8cb7-11eb-9b35-b64d2e7fad1f.png)

**Comment by erebe** [comment]
If you want to change the prompt, you can do it like that
`rofi -modi 'HERE:greenclip print' -show HERE -run-command '{cmd}'`

**Comment by joaopauloalbq** [comment]
Nice, thank you!
